/**
 * @file plugins/builtin-docx-export/index.js
 * Built-in **output**-export plugin: File ▸ Export output… ▸ Word (.docx).
 *
 * Registers through `app.outputExporters` and reads the Output pane via the
 * result-model surface (`app.results.getModel`, `getPlotPng`). officer builds a
 * .docx from R objects (not HTML), so this walks the model into a small content
 * model and generates R that assembles it: section titles → headings, each
 * result table → a real editable **flextable**, each plot → an embedded **PNG**
 * (Word renders SVG unreliably; the host rasterises via `getPlotPng`), notes →
 * paragraphs. Cell/heading text is encoded as `\u`/`\U`-escaped R string
 * literals, so no JSON/encoding round-trip is needed.
 *
 * The officer + flextable chain (verified present in WebR's repo) installs once
 * per session, on first use.
 */

/** @type {import('../../core/loader.js').PluginManifest} */
export const manifest = {
  id: 'builtin-docx-export',
  name: 'Word Output Export',
  version: '0.2.0',
  apiVersion: '0.1.0',
  category: 'Export',
  keywords: ['word', 'docx', 'report', 'output'],
  howto:
    'GUI: File ▸ Export output…, choose Word (.docx). Builds an editable Word report from the Output pane (tables → flextables, plots → embedded PNGs).\n' +
    'Used through the File menu, not a run command.',
  rPackages: ['officer', 'flextable'],
  outputExports: [{ label: 'Word (.docx)', extensions: ['.docx'], order: 20, export: 'exportDocx' }],
};

const DOCX_MIME = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

/**
 * Declarative output exporter: build a .docx from the result model (officer +
 * flextable in WebR) and return the bytes for the host to download.
 * @param {object} app
 * @param {{title: string}} opts
 * @returns {Promise<{filename: string, mimeType: string, data: Uint8Array}>}
 */
export async function exportDocx(app, { title }) {
  {
    const model = await app.results.getModel();

    // Build a flat content model; stage plot PNGs (host-rasterised) into WebR FS.
    const items = [
      { t: 'title', text: title || 'CrossTab Output' },
      { t: 'text', text: `Generated by CrossTab · ${new Date().toLocaleString()}` },
    ];
    let imgN = 0;
    for (const it of model) {
      if (it.kind === 'section') items.push({ t: 'heading', text: it.title });
      else if (it.kind === 'text') items.push({ t: 'text', text: htmlToText(it.html) });
      else if (it.kind === 'error') items.push({ t: 'text', text: it.message });
      else if (it.kind === 'table') items.push({ t: 'table', ...extractTable(it.html) });
      else if (it.kind === 'plot' || it.kind === 'chart') {
        const png = await app.results.getPlotPng(it.id);
        if (png && png.length) {
          const path = `/tmp/ct_out_img_${imgN}.png`;
          await app.webr.writeFile(path, png);
          const ar = svgAspect(it.svg);
          const w = 6.0;
          items.push({ t: 'image', path, w, h: Math.min(8, Number((w * ar).toFixed(2)) || 3.7) });
          imgN += 1;
        }
      } else if (it.kind === 'image' && /^data:image\//.test(String(it.src || ''))) {
        // Rasterised plot (e.g. from an R script) — decode the data URL to PNG bytes.
        const png = dataUrlToBytes(it.src);
        if (png && png.length) {
          const path = `/tmp/ct_out_img_${imgN}.png`;
          await app.webr.writeFile(path, png);
          items.push({ t: 'image', path, w: 6.0, h: 3.7 });
          imgN += 1;
        }
      }
    }

    await ensurePackages(app);
    const out = '/tmp/ct_out_report.docx';
    const r = await app.webr.run(modelToR(items, out));
    if (r.stderr && /error/i.test(r.stderr)) throw new Error(firstLine(r.stderr));
    const bytes = await app.webr.readFile(out);
    if (!bytes || bytes.length < 4) throw new Error('the document came back empty');

    return {
      filename: filenameFor(title, 'docx'),
      mimeType: DOCX_MIME,
      data: bytes,
    };
  }
}

/** Install officer/flextable once per session (cheap re-check via requireNamespace). */
async function ensurePackages(app) {
  const have = await app.webr.run(
    'as.logical(requireNamespace("officer", quietly=TRUE) && requireNamespace("flextable", quietly=TRUE))',
  );
  const ok = have?.result?.values?.[0] === true;
  if (!ok) {
    await app.results.appendText('Preparing Word export — installing document components (first time only)…');
    await app.webr.installPackages(['officer', 'flextable']);
  }
}

// --- model → R --------------------------------------------------------------

/** Generate the R that assembles the content model into a `.docx` via officer +
 * flextable and writes it to `outPath`. */
function modelToR(model, outPath) {
  const L = ['suppressMessages({ library(officer); library(flextable) })', 'doc <- read_docx()'];
  for (const it of model) {
    if (it.t === 'title') L.push(`doc <- body_add_par(doc, ${rstr(it.text)}, style = "heading 1")`);
    else if (it.t === 'heading') L.push(`doc <- body_add_par(doc, ${rstr(it.text)}, style = "heading 2")`);
    else if (it.t === 'text') L.push(`doc <- body_add_par(doc, ${rstr(it.text)}, style = "Normal")`);
    else if (it.t === 'image') L.push(`doc <- body_add_img(doc, src = ${rstr(it.path)}, width = ${it.w}, height = ${it.h})`);
    else if (it.t === 'table') {
      const cells = it.rows.flat();
      L.push(`.hdr <- c(${it.header.map(rstr).join(', ')})`);
      L.push(`.m <- matrix(c(${cells.length ? cells.map(rstr).join(', ') : '""'}), ncol = ${it.ncol}, byrow = TRUE)`);
      L.push('.df <- as.data.frame(.m, stringsAsFactors = FALSE); names(.df) <- paste0("c", seq_len(ncol(.df)))');
      L.push('.ft <- set_header_labels(flextable(.df), values = setNames(as.list(.hdr), names(.df)))');
      if (it.caption) L.push(`doc <- body_add_par(doc, ${rstr(it.caption)}, style = "Normal")`);
      L.push('doc <- body_add_flextable(doc, autofit(.ft))');
      L.push('doc <- body_add_par(doc, "", style = "Normal")');
    }
  }
  L.push(`print(doc, target = ${rstr(outPath)})`);
  L.push(`file.info(${rstr(outPath)})$size`);
  return L.join('\n');
}

/** Encode a JS string as a valid R double-quoted literal (non-ASCII via \u/\U). */
function rstr(s) {
  let out = '"';
  for (const ch of String(s)) {
    const code = ch.codePointAt(0);
    if (ch === '"') out += '\\"';
    else if (ch === '\\') out += '\\\\';
    else if (ch === '\n') out += '\\n';
    else if (ch === '\r') out += '\\r';
    else if (ch === '\t') out += '\\t';
    else if (code < 32) out += '\\u' + code.toString(16).padStart(4, '0');
    else if (code > 126) {
      out += code > 0xffff ? '\\U' + code.toString(16).padStart(8, '0') : '\\u' + code.toString(16).padStart(4, '0');
    } else out += ch;
  }
  return out + '"';
}

// --- HTML model parsing (in-iframe via DOMParser) ---------------------------

/** Parse a results `<table>` HTML string into {caption, header, rows, ncol}. */
function extractTable(html) {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const table = doc.querySelector('table');
  if (!table) return { caption: '', header: [''], rows: [], ncol: 1 };
  const caption = table.querySelector('caption')?.textContent.trim() ?? '';
  const headRows = [...table.querySelectorAll('thead tr')];
  let header = headRows.length
    ? [...headRows[headRows.length - 1].children].map((c) => c.textContent.trim())
    : [];
  let rows = [...table.querySelectorAll('tbody tr')].map((tr) =>
    [...tr.children].map((c) => c.textContent.trim()),
  );
  if (!rows.length) {
    rows = [...table.querySelectorAll('tr')]
      .filter((tr) => !tr.closest('thead'))
      .map((tr) => [...tr.children].map((c) => c.textContent.trim()));
  }
  const ncol = Math.max(header.length, ...(rows.length ? rows.map((r) => r.length) : [0]), 1);
  const pad = (a) => {
    const o = a.slice(0, ncol);
    while (o.length < ncol) o.push('');
    return o;
  };
  header = pad(header.length ? header : new Array(ncol).fill(''));
  rows = rows.map(pad);
  return { caption, header, rows, ncol };
}

/** Flatten a rendered HTML fragment to plain text. */
function htmlToText(html) {
  return new DOMParser().parseFromString(String(html ?? ''), 'text/html').body.textContent.trim();
}

/** Height/width ratio of an SVG from its viewBox (or width/height), default 0.62. */
/** Decode a `data:image/…;base64,…` URL to bytes for embedding. */
function dataUrlToBytes(url) {
  const i = String(url).indexOf(',');
  if (i < 0) return null;
  const bin = atob(url.slice(i + 1));
  const out = new Uint8Array(bin.length);
  for (let j = 0; j < bin.length; j++) out[j] = bin.charCodeAt(j);
  return out;
}

function svgAspect(svg) {
  try {
    const el = new DOMParser().parseFromString(String(svg ?? ''), 'image/svg+xml').querySelector('svg');
    const vb = el?.getAttribute('viewBox');
    if (vb) {
      const p = vb.split(/[\s,]+/).map(Number);
      if (p.length === 4 && p[2] > 0) return p[3] / p[2];
    }
    const w = parseFloat(el?.getAttribute('width'));
    const h = parseFloat(el?.getAttribute('height'));
    if (w > 0 && h > 0) return h / w;
  } catch {
    /* fall through */
  }
  return 0.62;
}

function firstLine(s) {
  return String(s).split('\n').find((l) => l.trim()) ?? String(s);
}

function filenameFor(title, ext) {
  const base =
    String(title || 'crosstab-output')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'crosstab-output';
  return `${base}.${ext}`;
}
