/**
 * @file output-export.js
 * Export the **Output pane** (analysis results) as a shareable artifact — the
 * write-up half of export, distinct from *data* export (`app.exporters`).
 *
 * The results live in an *open* shadow root as append-only DOM (sections,
 * tables, inline-SVG plots, notes — see {@link results-pane.js}). There is no
 * separate result model, so the faithful, WYSIWYG approach is to **clone that
 * live markup** and reuse the pane's own stylesheet. Both targets fall out of
 * one renderer:
 *   - **HTML** — write the cloned report to a self-contained `.html` file.
 *   - **PDF** — render the same report into a hidden same-origin iframe and
 *     `print()` it; the user picks "Save as PDF". Zero-dependency, native, and
 *     works on iPad Safari (Save to Files). Printing from a normal-DOM iframe
 *     also sidesteps the shadow-DOM-in-print wrinkle.
 *
 * Host-owned (a sandboxed plugin can't read the results DOM or trigger a
 * download/print), surfaced as **File ▸ Export output…**.
 */

import { downloadFile } from './export-service.js';

export class OutputExport {
  /** The results-pane host element (carries the open shadow root). */
  #host;
  /** @type {import('./menu-shell.js').MenuShell} */
  #menus;
  /** @type {import('./project-sync.js').ProjectSync} */
  #projects;
  /** ResultsPane#api, for surfacing errors. @type {{appendError: Function}} */
  #results;

  /**
   * @param {Object} deps
   * @param {HTMLElement} deps.resultsHost - The element hosting the results shadow root.
   * @param {import('./menu-shell.js').MenuShell} deps.menus
   * @param {import('./project-sync.js').ProjectSync} deps.projects
   * @param {{appendError: Function}} deps.results - ResultsPane#api.
   */
  constructor({ resultsHost, menus, projects, results }) {
    this.#host = resultsHost;
    this.#menus = menus;
    this.#projects = projects;
    this.#results = results;
  }

  activate() {
    this.#menus.register({
      id: 'core:export-output',
      path: ['File'],
      label: 'Export output…',
      order: 10,
      command: () => this.#open(),
    });
  }

  // --- output inspection -----------------------------------------------------

  /** The `.results-root` element inside the open shadow root, or null. */
  #resultsRoot() {
    return this.#host?.shadowRoot?.querySelector('.results-root') ?? null;
  }

  /** Whether there's any real output (not just the empty-state placeholder). */
  #hasOutput() {
    const root = this.#resultsRoot();
    if (!root) return false;
    if (root.querySelector('[data-empty-state]') && root.childElementCount <= 1) return false;
    return root.childElementCount > 0;
  }

  #open() {
    if (!this.#hasOutput()) {
      this.#results.appendError('Export output: there is no output yet. Run an analysis first.');
      return;
    }
    this.#showDialog();
  }

  #defaultTitle() {
    return this.#projects?.activeName ?? 'CrossTab Output';
  }

  // --- report building -------------------------------------------------------

  /** Build a self-contained report HTML document string from the live output. */
  #buildReport(title) {
    const root = this.#resultsRoot();
    const clone = root.cloneNode(true);
    // Strip interactive-only affordances that don't belong in a static report.
    for (const b of clone.querySelectorAll('.results-plot__redraw, .results-plot__save, button')) {
      b.remove();
    }
    // Drop the resize grip on plot boxes (keep their size).
    for (const p of clone.querySelectorAll('.results-plot')) p.style.resize = 'none';

    const paneStyles = this.#host?.shadowRoot?.querySelector('style')?.textContent ?? '';
    const safeTitle = escapeHtml(title || 'CrossTab Output');
    const when = new Date().toLocaleString();
    return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safeTitle}</title>
<style>
${paneStyles}
:root { color-scheme: light; }
body { margin: 0; background: #fff; }
.report-header {
  font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif;
  padding: 24px 16px 0; color: #1a1a1a;
}
.report-header h1 { margin: 0 0 2px; font-size: 22px; }
.report-header .report-meta { color: #666; font-size: 12px; }
.report-header hr { border: 0; border-top: 1px solid #ccc; margin: 14px 0 0; }
@media print {
  .results-plot, table, .results-block { break-inside: avoid; }
  .results-section { break-inside: avoid-page; }
  @page { margin: 18mm 14mm; }
}
</style>
</head>
<body>
<header class="report-header">
  <h1>${safeTitle}</h1>
  <div class="report-meta">Generated by CrossTab · ${escapeHtml(when)}</div>
  <hr>
</header>
${clone.outerHTML}
</body>
</html>`;
  }

  // --- targets ---------------------------------------------------------------

  #exportHtml(title) {
    try {
      const html = this.#buildReport(title);
      downloadFile(filenameFor(title, 'html'), 'text/html;charset=utf-8', html);
    } catch (err) {
      console.error('[output-export] HTML failed', err);
      this.#results.appendError(`Export to HTML failed: ${err.message}`);
    }
  }

  /** Render the report into a hidden same-origin iframe and print it. The user
   * chooses "Save as PDF" in the print dialog. */
  #exportPdf(title) {
    let html;
    try {
      html = this.#buildReport(title);
    } catch (err) {
      console.error('[output-export] PDF build failed', err);
      this.#results.appendError(`Export to PDF failed: ${err.message}`);
      return;
    }
    const iframe = document.createElement('iframe');
    iframe.setAttribute('aria-hidden', 'true');
    iframe.style.cssText = 'position:fixed; right:0; bottom:0; width:0; height:0; border:0;';
    document.body.append(iframe);
    const cleanup = () => setTimeout(() => iframe.remove(), 1000);
    iframe.addEventListener('load', () => {
      const win = iframe.contentWindow;
      // Print once laid out (tables + inline SVG are synchronous, so a frame is enough).
      win.requestAnimationFrame(() => {
        try {
          win.focus();
          win.print();
        } catch (err) {
          console.error('[output-export] print failed', err);
          this.#results.appendError(`Print failed: ${err.message}`);
        }
        cleanup();
      });
    });
    const doc = iframe.contentDocument;
    doc.open();
    doc.write(html);
    doc.close();
  }

  // --- dialog ----------------------------------------------------------------

  #showDialog() {
    const dialog = document.createElement('dialog');
    dialog.className = 'ct-dialog';
    dialog.innerHTML = `
      <form method="dialog" class="ct-dialog__form ct-export">
        <h2 class="ct-dialog__title">Export output</h2>
        <p class="ct-dialog__hint">Save the Output pane (tables, plots, notes) as a report.</p>
        <label class="ct-field">Report title
          <input name="title" type="text" value="${escapeAttr(this.#defaultTitle())}">
        </label>
        <menu class="ct-dialog__buttons ct-export__buttons">
          <button value="cancel" type="submit">Cancel</button>
          <button value="html" type="submit">Download HTML</button>
          <button value="pdf" type="submit" class="ct-dialog__primary">Print / Save PDF</button>
        </menu>
      </form>`;
    dialog.addEventListener('close', () => {
      const action = dialog.returnValue;
      const title = dialog.querySelector('input[name="title"]')?.value.trim() || this.#defaultTitle();
      dialog.remove();
      if (action === 'html') this.#exportHtml(title);
      else if (action === 'pdf') this.#exportPdf(title);
    });
    document.body.append(dialog);
    dialog.showModal();
  }
}

// --- helpers ---------------------------------------------------------------

function escapeHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
function escapeAttr(s) {
  return escapeHtml(s).replace(/"/g, '&quot;');
}

/** A filesystem-friendly filename from a title + extension. */
function filenameFor(title, ext) {
  const base =
    String(title || 'crosstab-output')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'crosstab-output';
  return `${base}.${ext}`;
}
