/**
 * @file plugins/builtin-html-export/index.js
 * Built-in **output**-export plugin: File ▸ Export output… ▸ HTML.
 *
 * Registers through `app.outputExporters` (the output-export extension point,
 * mirror of `app.exporters` for data) and reads the Output pane through the
 * result-model surface (`app.results.getModel` / `getStyles`) rather than
 * scraping host DOM — so output export honours "everything is a plugin". Builds
 * a self-contained `.html` report (tables + inline vector plots + notes) reusing
 * the pane's own stylesheet, and hands the engine the bytes to download.
 */

/** @type {import('../../core/loader.js').PluginManifest} */
export const manifest = {
  id: 'builtin-html-export',
  name: 'HTML Output Export',
  version: '0.2.0',
  apiVersion: '0.1.0',
  category: 'Export',
  keywords: ['html', 'report', 'output'],
  rPackages: [],
  outputExports: [{ label: 'HTML (.html)', extensions: ['.html'], order: 10, export: 'exportHtml' }],
};

/**
 * Declarative output exporter: render the result model to a standalone HTML
 * report and return the bytes for the host to download.
 * @param {object} app
 * @param {{title: string}} opts
 * @returns {Promise<{filename: string, mimeType: string, data: string}>}
 */
export async function exportHtml(app, { title }) {
  const model = await app.results.getModel();
  const css = await app.results.getStyles();
  return {
    filename: filenameFor(title, 'html'),
    mimeType: 'text/html;charset=utf-8',
    data: buildHtml(model, css, title),
  };
}

/** Render the result model into a standalone HTML document, reusing the pane's
 * canonical stylesheet so the report matches the on-screen output. */
function buildHtml(model, css, title) {
  const safeTitle = esc(title || 'CrossTab Output');
  const when = new Date().toLocaleString();

  let body = '<div class="results-root">';
  let inSection = false;
  for (const it of model) {
    if (it.kind === 'section') {
      if (inSection) body += '</section>';
      body += `<section class="results-section"><h2 class="results-section__title">${esc(it.title)}</h2>`;
      inSection = true;
    } else if (it.kind === 'text') {
      body += `<div class="results-block results-note">${it.html ?? ''}</div>`;
    } else if (it.kind === 'table') {
      body += `<div class="results-block">${it.html ?? ''}</div>`;
    } else if (it.kind === 'plot' || it.kind === 'chart') {
      // Plain block (no resize box) so the report is static; the SVG keeps its
      // aspect via the pane's base `svg` rule. Data-driven charts carry their
      // last-rendered SVG in `it.svg`, same as baked plots.
      body += `<div class="results-block">${it.svg ?? ''}</div>`;
    } else if (it.kind === 'error') {
      body += `<div class="results-block results-error">${esc(it.message ?? '')}</div>`;
    }
  }
  if (inSection) body += '</section>';
  body += '</div>';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safeTitle}</title>
<style>
${css}
:root { color-scheme: light; }
body { margin: 0; background: #fff; }
.report-header { font: 14px/1.5 system-ui, -apple-system, "Segoe UI", sans-serif; padding: 24px 16px 0; color: #1a1a1a; }
.report-header h1 { margin: 0 0 2px; font-size: 22px; }
.report-header .report-meta { color: #666; font-size: 12px; }
.report-header hr { border: 0; border-top: 1px solid #ccc; margin: 14px 0 0; }
@media print {
  .results-plot, table, .results-block { break-inside: avoid; }
  .results-section { break-inside: avoid-page; }
  @page { margin: 18mm 14mm; }
}
</style>
</head>
<body>
<header class="report-header">
  <h1>${safeTitle}</h1>
  <div class="report-meta">Generated by CrossTab · ${esc(when)}</div>
  <hr>
</header>
${body}
</body>
</html>`;
}

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function filenameFor(title, ext) {
  const base =
    String(title || 'crosstab-output')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'crosstab-output';
  return `${base}.${ext}`;
}
